### ISSUE TITLE
Installation problem with Python 3.12

### ISSUE THREAD

**Issue by pablo-oyola** [JoseRuedaRueda/ScintSuite#6]
When installing the library under python 3.12, the library "pyFFTW" raises an error during installation:
```
Collecting pyfftw>=0.13.1 (from ScintSuite)
  Using cached pyFFTW-0.13.1.tar.gz (114 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/pablooyola/.anaconda3/envs/ascot-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/pablooyola/.anaconda3/envs/ascot-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pablooyola/.anaconda3/envs/ascot-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/pablooyola/.anaconda3/envs/ascot-env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/pablooyola/.anaconda3/envs/ascot-env/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-t90b9wp7/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-t90b9wp7/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-t90b9wp7/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

The above error seems to be linked to an update on the python 3.12 setuptools library that pyFFTW is not updating. In python 3.12 the package `importlib` has been modified:
```
importlib
Many previously deprecated cleanups in [importlib](https://docs.python.org/3/library/importlib.html#module-importlib) have now been completed:

References to, and support for module_repr() has been removed. (Contributed by Barry Warsaw in [gh-97850](https://github.com/python/cpython/issues/97850).)

importlib.util.set_package, importlib.util.set_loader and importlib.util.module_for_loader have all been removed. (Contributed by Brett Cannon and Nikita Sobolev in [gh-65961](https://github.com/python/cpython/issues/65961) and [gh-97850](https://github.com/python/cpython/issues/97850).)

Support for find_loader() and find_module() APIs have been removed. (Contributed by Barry Warsaw in [gh-98040](https://github.com/python/cpython/issues/98040).)

importlib.abc.Finder, pkgutil.ImpImporter, and pkgutil.ImpLoader have been removed. (Contributed by Barry Warsaw in [gh-98040](https://github.com/python/cpython/issues/98040).)
```

And hence the error. I tried following our beloved ~~God~~  [StackOverflow](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean) on this issue, but it does not seem to work...

**Comment by JoseRuedaRueda** [comment]
I could install the Suite in python 3.13, so I guess this is corrected? I close this issue. If it is not corrected, please reopen
